INSERT INTO notes(note_title, content, folder_id)
VALUES
    ('Cat', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 1),
    ('Car', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 2),
    ('Apple', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 3),
    ('Carrot', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 4),
    ('Cake', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 5),
    ('Walk Dog', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 6),
    ('Walmart', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 7),
    ('Skirt', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 8),
    ('Ball', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 9),
    ('Hamster', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 1),
    ('Tiger', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 1),
    ('Cow', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 1),
    ('Cupcakes', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 5),
    ('Pie', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 5),
    ('Chocolate', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 5),
    ('Pear', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 3),
    ('Orange', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 3),
    ('Watermelon', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 3),
    ('Grapes', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 3),
    ('Peanut Brittle', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand in the way of sinners, nor sit in the seat of scoffers; but his delight is in Yahweh''s law. On his law he meditates day and night. He will be like a tree planted by the streams of water, that brings forth its', 5);
    